### PR TITLE
Support for more browsers

### PR DESCRIPTION
**Pull request by epmatsw**
Firefox Developer edition is now detected automatically if a normal Firefox installation is not detected.

Chrome Canary can be launched with the name of 'canary'.

Both of these only work on OSX because the library used to detect browsers in Windows doesn't have support for these browsers. Bummer.

### CODE REVIEW

**Comment by epmatsw** [comment]
Oh whoops. Did not mean to open this into the main branch.

**Comment by chrisbreiding** [comment]
Any reason not to try and get this merged upstream? Would be really useful.

**Comment by epmatsw** [comment]
Some of the stuff underneath it has changed since I made these changes. I can redo them real quick though.

**Comment by epmatsw** [comment]
Actually, it looks like a more recent PR for Canary support is just sitting there.

**Pull request closed without merging**
